<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Note;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(array $terms, $limit = 10)
    {
        if (empty($terms)) {
            return $this->findBy([], ['id' => 'desc'], $limit);
        }

        $query = 'SELECT n.* FROM note n';
        $query .= ' WHERE (n.title LIKE :term_0 OR EXISTS(
        SELECT * FROM tag t INNER JOIN note_tag nt ON nt.tag_id = t.id AND nt.note_id = n.id 
        WHERE t.name LIKE :term_0)) ';

        for ($i = 1; $i < count($terms); ++$i) {
            $query .= ' AND (n.title LIKE :term_' . $i . ' OR EXISTS(
        SELECT * FROM tag t INNER JOIN note_tag nt ON nt.tag_id = t.id AND nt.note_id = n.id 
        WHERE t.name LIKE :term_' . $i . '))';
        }
        $query .= ' ORDER BY n.id DESC LIMIT :limit ';

        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata(Note::class, 'n');
        $params = array_combine(
            array_map(function ($v) {
                return 'term_' . $v;
            }, array_keys($terms)),
            array_map(function ($v) {
                return '%' . $v . '%';
            }, $terms));
        $params['limit'] = $limit;

        return $this->getEntityManager()->createNativeQuery($query, $rsm)->setParameters($params)->getResult();
    }

}
