<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Symfony\Component\VarDumper\VarDumper;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(array $terms, $limit = 10)
    {
        if (empty($terms)) {
            return $this->findBy([], ['id' => 'desc'], $limit);
        }

        $query = 'SELECT p.* FROM project p';
        $query .= ' WHERE (p.name LIKE :term_0 OR EXISTS(
        SELECT * FROM tag t INNER JOIN project_tag pt ON pt.tag_id = t.id AND pt.project_id = p.id 
        WHERE t.name LIKE :term_0)) ';

        for ($i = 1; $i < count($terms); ++$i) {
            $query .= ' AND (p.name LIKE :term_' . $i . ' OR EXISTS(
        SELECT * FROM tag t INNER JOIN project_tag pt ON pt.tag_id = t.id AND pt.project_id = p.id 
        WHERE t.name LIKE :term_' . $i . '))';
        }
        $query .= ' ORDER BY p.id DESC LIMIT :limit ';

        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata(Project::class, 'p');
        $params = array_combine(
            array_map(function ($v) {
                return 'term_' . $v;
            }, array_keys($terms)),
            array_map(function ($v) {
                return '%' . $v . '%';
            }, $terms));
        $params['limit'] = $limit;

        return $this->getEntityManager()->createNativeQuery($query, $rsm)->setParameters($params)->getResult();
    }
}
