services:
    app.form.type.tags:
        class: AppBundle\Form\Type\TagsType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    app.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        tags:
            - { name: twig.extension }
    app.event_listener.request_listener:
        class: AppBundle\EventListener\RequestListener
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: kernel.request }